### ISSUE TITLE
How to check if Snappy library is used

### ISSUE THREAD

**Issue by ghost** [wmorgan/leveldb-ruby#9]
hi,

i installed snappy library (compression library) on my macbook pro (osx 10.7.3 + xcode 4.2.1) using homebrew

```
brew install snappy
```

which will install snappy into `/usr/local/Cellar/snappy/1.0.4`
homebrew adds these path to $PATH
my question is, how to get the information if snappy is used properly?

**Comment by ghost** [comment]
snappy is used.
i faced off an error message about snappy

```
/Users/fibric/.rvm/rubies/ruby-1.9.3-p0/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/fibric/Projects/StoreBox/lib/store_box.rb
dyld: lazy symbol binding failed: Symbol not found: __ZN6snappy19MaxCompressedLengthEm
  Referenced from: /Users/fibric/.rvm/gems/ruby-1.9.3-p0@leveldb/gems/leveldb-ruby-0.10/lib/leveldb/leveldb.bundle
  Expected in: flat namespace

dyld: Symbol not found: __ZN6snappy19MaxCompressedLengthEm
  Referenced from: /Users/fibric/.rvm/gems/ruby-1.9.3-p0@leveldb/gems/leveldb-ruby-0.10/lib/leveldb/leveldb.bundle
  Expected in: flat namespace


Process finished with exit code 133
```

i used this code in 

``` ruby```
db = LevelDB::DB.new 'asdf'
db.put :key, :value
db.get :key
```

**Comment by ghost** [comment]
i found the problem, i guess.

a clean db will work properly. reusing an existing db will cause the error message (from above).
if i create a new instance (given pathname is not used from any leveldb before) then everything works.
if i restart my app which will reuse the last used leveldb pathname then i face off this error message.

**Comment by wmorgan** [comment]
I'm not even sure why Snappy is being called in the first place. From what I can tell, the OS X-specific code bits explicitly avoid using snappy. You may wish to talk to the LevelDB authors. Another experiment would be to see whether a pure C++ client on OS X works, i.e. whether it's the Ruby bindings that are introducing the issues.

Sorry I don't have a better answer for you.

**Comment by ghost** [comment]
no problem. i'll ask in google groups about that situation.
i can't fix it by my self because i have almost zero knowledge about c/c++

**Comment by craic** [comment]
I ran into the same issue - (Ruby 1.9.2, Mac OS X 10.6.8)

The issue was that I had installed the snappy library (using just ./configure; make; sudo make install). Installing the leveldb-ruby gem after this gave me the same error:

dyld: lazy symbol binding failed: Symbol not found: __ZN6snappy19MaxCompressedLengthEm
  Referenced from: /Users/jones/.rvm/gems/ruby-1.9.2-p0/gems/leveldb-ruby-0.10/lib/leveldb/leveldb.bundle
  Expected in: flat namespace

Poking around in the Leveldb source, included in the gem, I saw that this is referenced from a couple of include files, but only when it finds that the snappy library is installed.

So I uninstalled Snappy with a 'sudo make uninstall' from the snappy build directory.
I then did a gem 'uninstall leveldb-ruby' followe by a fresh 'gem install leveldb-ruby' 

Problem solved !

I presume that the leveldb installation will no longer use snappy compression (I don't think there is any snappy code in the included leveldb code) - that's not a problem for me (in the short term at least)

--Rob Jones

**Comment by ghost** [comment]
I also removed snappy from search path and all my problems are gone. Of cause snappy is not the best compression library out there but the fastest one for plain text. I hope that snappy can be combined with leveldb-ruby rather sooner than later ;-)
